title: CLPO
description: Guided Self-Evolution for Mathematical Reasoning
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
baseurl: ""
url: "https://csuking.github.io"

# Social links
github_username: csuking
twitter_username: your-twitter

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
